### ISSUE TITLE
safenuget is no longer maintained

### ISSUE THREAD

**Issue by SimonCropp** [MyGet/MyGetDocs#117]
Re this page https://docs.myget.org/docs/how-to/checking-nuget-package-vulnerabilities-with-owasp-safenuget

it seems safenuget is no longer maintained. https://github.com/OWASP/SafeNuGet/issues/16

**Comment by digitalcoyote** [comment]
I'm working on a project that could be used as an alternative: NuGetDefense. Works for packages.config and project package references. It currently checks OSS Index for vulnerabilities, but more sources are in the works.
