### ISSUE TITLE
Reference: Create MyGet Gallery Page

### ISSUE THREAD

**Issue by gep13** [myget/MyGetDocs#31]
Provide guidance on how to publish a feed in the MyGet Gallery, and hook up a GitHub readme file or create a new one on MyGet.

**Comment by ferventcoder** [comment]
@gep13 @maartenba @xavierdecoster are these still valid? All of the up for grabs items?

**Comment by xavierdecoster** [comment]
This one still is valid :) Verifying the other issues with this label.

**Comment by ferventcoder** [comment]
thanks!

**Comment by kreynazpm** [comment]
Could you provide additional information on what you want for this page; possibly a list of steps on how to publish a feed?

**Comment by xavierdecoster** [comment]
Figured I'd simply had to write this one. Thanks for pushing on this one :smiley: 
Feel free to provide your feedback and suggestions on the gallery reference page and open issues for improvements.
http://docs.myget.org/docs/reference/myget-gallery
