### ISSUE TITLE
Restoring accidentally deleted packages from backup?

### ISSUE THREAD

**Issue by smaglio81** [MyGet/MyGetDocs#83]
Hello,

I was searching through the Docs and didn't find an answer to a somewhat odd question:

**If something went horribly wrong and all packages on a feed were deleted, is there a way to get the lost packages restored from backup?**

The closest answer I found was on the [FAQ ](https://docs.myget.org/docs/reference/faq) page's _Where is my data stored?_ answer, which mentioned backups.

> All free and paid plans are hosted in this location, with backups in the North Europe region, near Dublin, Ireland.

But I read to mean backups of the websites and account information. It didn't seem to indicate that it was keeping backups of the listed packages on a daily or weekly basis. Is that something that is offered?

Maybe this is already answered in the FAQ and I'm just missing it.

**Comment by maartenba** [comment]
@smaglio81 for these matters, please get in touch with support. They will be able to help you there.
